# 基础模型实验配置
model:
  base_model_path: "/mnt/data1/FT/inspire_data_prep/models/gemma2-2b"
  adapter_path: "/mnt/data1/TC/TextClassDemo/LLaMA-Factory/gemma_multi"
  use_lora: true

data:
  data_path: "/mnt/data1/TC/TextClassDemo/data/ohsumed/ohsumed_test_Cxx.json"
  dataset_name: ohsumed
  num_classes: 23

generation:
  max_new_tokens: 1024
  temperature: 0.4
  top_p: 0.95
  do_sample: true

training:
  batch_size: 64
  vote_count: 1

output:
  base_output_dir: "./outputs/multi"
  experiment_name: "gemma2-2b_ohsumed_base_direct"