# TREC LoRA直接评估配置
model:
  base_model_path: "/mnt/data1/FT/inspire_data_prep/models/LLM-Research/Meta-Llama-3.1-70B-Instruct"
  adapter_path: "/mnt/data1/TC/TextClassDemo/LLaMA-Factory/llama3.1-8b_trec_direct_lora"
  use_lora: false

data:
  data_path: "/mnt/data1/TC/TextClassDemo/data/TREC/TREC_Test_Cxx.json"
  dataset_name: TREC
  num_classes: 6

generation:
  max_new_tokens: 1024
  temperature: 0.4
  top_p: 0.9
  do_sample: false

training:
  batch_size: 128
  vote_count: 1

output:
  base_output_dir: "./outputs"
  experiment_name: "llama-3.1-70b-instruct_trec_base_direct" 