# 默认配置文件
# 模型配置
model:
  base_model_path: "/mnt/data1/TC/TextClassDemo/llama3.1-8b"
  adapter_path: "/mnt/data1/TC/TextClassDemo/LLaMA-Factory/llama3.1-8b_ohsumed_lora_english_zeroshotCoT"
  use_lora: true

# 数据配置
data:
  data_path: "/mnt/data1/TC/TextClassDemo/data/ohsumed_Test_alpaca_noCoT_updated.json"
  dataset_name: ohsumed
  num_classes: 23

# 生成参数配置
generation:
  max_new_tokens: 256
  temperature: 0.4
  top_p: 0.9
  do_sample: false

# 训练配置
training:
  batch_size: 512
  vote_count: 5

# 输出配置
output:
  base_output_dir: "./outputs"
  experiment_name: "default_experiment"