# 基础模型实验配置
model:
  base_model_path: "/mnt/data1/TC/TextClassDemo/llama3.1-8b"
  adapter_path: "/mnt/data1/TC/TextClassDemo/LLaMA-Factory/llama3.1-8b_r52_direct_lora"
  use_lora: true

data:
  data_path: "/mnt/data1/TC/TextClassDemo/data/R52/R52_Test_Cxx.json"
  dataset_name: r52

generation:
  max_new_tokens: 256
  temperature: 0.4
  top_p: 0.9
  do_sample: false

training:
  batch_size: 512

output:
  base_output_dir: "./outputs"
  experiment_name: "r52_lora_direct"